Repository gardener/etcd-backup-restore, pull requests merged in 2018-12, with the labels that each got.

#77 Add Shreyas Rao to maintainers.
  CODEOWNERS
Labels: needs/lgtm

#59 Add helm chart
  chart/Chart.yaml
  chart/templates/etcd-bootstrap-configmap.yaml
  chart/templates/etcd-client-service.yaml
  chart/templates/etcd-statefulset.yaml
  chart/values.yaml
Labels: component/etcd-backup-restore, exp/beginner, kind/enhancement, needs/ok-to-test, platform/all, priority/normal, reviewed/lgtm, size/s, status/in-progress

#86 Avoid duplicate full snapshot
  pkg/snapshot/snapshotter/snapshotter.go
Labels: area/performance, kind/enhancement, needs/ok-to-test, platform/all, priority/normal, reviewed/lgtm, size/xs
