Repository gardener/etcd-backup-restore, pull requests merged in 2018-07, with the labels that each got.

#37 Fix pipeline-definition
  .ci/pipeline_definitions
Labels: reviewed/lgtm, reviewed/ok-to-test

#35 Change in exponential garbage collecto algo
  pkg/snapshot/snapshotter/garbagecollector.go
Labels: exp/intermediate, platform/all, priority/normal, size/s, status/in-progress

#30 Integration ginkgo based test and script files.
  .ci/integration_test
  .ci/unit_test
  Gopkg.lock
  Gopkg.toml
  test/e2e/integration/cloud_backup_test.go
  test/e2e/integration/integration_suite_test.go
  test/e2e/integration/utils.go
  vendor/github.com/bgentry/speakeasy/LICENSE
  vendor/github.com/bgentry/speakeasy/LICENSE_WINDOWS
  vendor/github.com/bgentry/speakeasy/speakeasy.go
  vendor/github.com/bgentry/speakeasy/speakeasy_unix.go
  vendor/github.com/bgentry/speakeasy/speakeasy_windows.go
  vendor/github.com/coreos/etcd/auth/nop.go
  vendor/github.com/coreos/etcd/auth/store.go
  vendor/github.com/coreos/etcd/clientv3/client.go
  vendor/github.com/coreos/etcd/clientv3/watch.go
  vendor/github.com/coreos/etcd/cmd/functional
  vendor/github.com/coreos/etcd/embed/config.go
  vendor/github.com/coreos/etcd/embed/etcd.go
  vendor/github.com/coreos/etcd/etcdserver/apply.go
  vendor/github.com/coreos/etcd/etcdserver/apply_v2.go
  vendor/github.com/coreos/etcd/etcdserver/config.go
  vendor/github.com/coreos/etcd/etcdserver/etcdserverpb/raft_internal_stringer.go
  vendor/github.com/coreos/etcd/etcdserver/metrics.go
  vendor/github.com/coreos/etcd/etcdserver/raft.go
  vendor/github.com/coreos/etcd/etcdserver/server.go
  vendor/github.com/coreos/etcd/etcdserver/stats/server.go
  vendor/github.com/coreos/etcd/etcdserver/util.go
  vendor/github.com/coreos/etcd/etcdserver/v3_server.go
  vendor/github.com/coreos/etcd/mvcc/watchable_store.go
  vendor/github.com/coreos/etcd/mvcc/watcher_group.go
  vendor/github.com/coreos/etcd/pkg/flags/flag.go
  vendor/github.com/coreos/etcd/pkg/flags/strings.go
  vendor/github.com/coreos/etcd/pkg/flags/urls.go
  vendor/github.com/coreos/etcd/pkg/tlsutil/cipher_suites.go
  vendor/github.com/coreos/etcd/pkg/transport/listener.go
  vendor/github.com/coreos/etcd/pkg/transport/proxy.go
  vendor/github.com/coreos/etcd/version/version.go
  vendor/github.com/dustin/go-humanize/LICENSE
  vendor/github.com/dustin/go-humanize/big.go
  vendor/github.com/dustin/go-humanize/bigbytes.go
  vendor/github.com/dustin/go-humanize/bytes.go
  vendor/github.com/dustin/go-humanize/comma.go
  vendor/github.com/dustin/go-humanize/commaf.go
  vendor/github.com/dustin/go-humanize/ftoa.go
  vendor/github.com/dustin/go-humanize/humanize.go
  vendor/github.com/dustin/go-humanize/number.go
  vendor/github.com/dustin/go-humanize/ordinals.go
  vendor/github.com/dustin/go-humanize/si.go
  vendor/github.com/dustin/go-humanize/times.go
Labels: kind/test, platform/aws, priority/normal, size/m

#40 Fix integration test for limit based garbage collection
  pkg/initializer/initializer.go
  pkg/snapshot/snapshotter/garbagecollector.go
  pkg/snapstore/gcs_snapstore.go
  test/e2e/integration/cloud_backup_test.go
Labels: kind/test, reviewed/lgtm

#42 Adding documentation for incremental snapshot and garbage collection.
  README.md
Labels: reviewed/lgtm
