Repository gardener/etcd-backup-restore, pull requests merged in 2019-09, with the labels that each got.

#193 Expose etcdbr_snapshot_required metric
  README.md
  cmd/server.go
  doc/usage/metrics.md
  pkg/metrics/metrics.go
  pkg/snapshot/restorer/restorer.go
  pkg/snapshot/snapshotter/snapshotter.go
Labels: area/monitoring, component/etcd-backup-restore, kind/enhancement, needs/lgtm, needs/ok-to-test, needs/review, platform/all

#197 Fix oss object listing
  pkg/snapstore/oss_snapstore.go
Labels: needs/ok-to-test

#198 Fix/oss object list
  pkg/snapstore/oss_snapstore.go
Labels: needs/ok-to-test

#173 Added negative tests for restore of snapshots
  .ci/unit_test
  pkg/miscellaneous/miscellaneous.go
  pkg/snapshot/restorer/restorer.go
  pkg/snapshot/restorer/restorer_suite_test.go
  pkg/snapshot/restorer/restorer_test.go
Labels: area/quality, component/etcd-backup-restore, exp/intermediate, kind/test, needs/ok-to-test, platform/all, priority/normal, reviewed/lgtm

#199 Expose etcdbr_snapshot_required metric
  README.md
  cmd/server.go
  doc/usage/metrics.md
  pkg/metrics/metrics.go
  pkg/snapshot/restorer/restorer.go
  pkg/snapshot/snapshotter/snapshotter.go
Labels: needs/ok-to-test

#200 Fix the revision consitency check error handling
  README.md
  doc/development/new_cp_support.md
  pkg/initializer/initializer.go
  pkg/initializer/validator/datavalidator.go
  pkg/initializer/validator/datavalidator_test.go
  pkg/initializer/validator/types.go
  pkg/snapshot/restorer/restorer.go
  pkg/snapshot/restorer/restorer_test.go
  pkg/snapshot/snapshotter/snapshotter.go
  pkg/snapstore/failed_snapstore.go
  pkg/snapstore/types.go
  pkg/snapstore/utils.go
Labels: area/backup, component/etcd-backup-restore, kind/bug, needs/lgtm, needs/ok-to-test, needs/review, platform/all, priority/critical

#203 Add document for manual restoration steps
  README.md
  doc/proposals/restoration.md
  doc/usage/manual_restoration.md
Labels: area/documentation, area/ops-productivity, component/etcd-backup-restore, needs/lgtm, needs/ok-to-test, needs/review

#202 Fix restoration metric
  pkg/initializer/initializer.go
Labels: area/monitoring, component/etcd-backup-restore, kind/bug, needs/ok-to-test, platform/all, reviewed/lgtm, size/xs

#192 [Feature] Expose api to trigger out-of-schedule delta snapshot
  .ci/unit_test
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/pull_request_template.md
  Makefile
  pkg/server/httpAPI.go
  pkg/snapshot/snapshotter/snapshotter.go
  pkg/snapshot/snapshotter/snapshotter_test.go
  pkg/snapshot/snapshotter/types.go
  test/utils/utils.go
Labels: area/backup, exp/beginner, kind/api-change, needs/lgtm, needs/ok-to-test, needs/review, platform/all, priority/normal
