Repository gardener/etcd-backup-restore, pull requests merged in 2019-06, with the labels that each got.

#165 Fix error handling for initial delta snapshot
  cmd/server.go
Labels: area/backup, component/etcd-backup-restore, needs/ok-to-test, needs/review, platform/all, reviewed/lgtm

#166 Fix error handling for initial delta snapshot
  cmd/server.go
  pkg/snapstore/abs_snapstore.go
Labels: needs/ok-to-test, reviewed/lgtm

#168 Proposal to handle high watch event rate.
  doc/images/profile-fast-drain.png
  doc/images/profile-high-rate-events.png
  doc/proposals/high_watch_event_ingress_rate.md
Labels: needs/ok-to-test
