Repository gardener/etcd-backup-restore, pull requests merged in 2020-04, with the labels that each got.

#215 Fix integration test setup script
  .ci/integration_test
Labels: kind/bug, needs/lgtm, needs/ok-to-test, needs/review

#214 Return metadata for latest and triggered snapshots
  pkg/defragmentor/defrag.go
  pkg/defragmentor/defrag_test.go
  pkg/server/backuprestoreserver.go
  pkg/server/httpAPI.go
  pkg/server/types.go
  pkg/snapshot/snapshotter/snapshotter.go
  pkg/snapshot/snapshotter/snapshotter_test.go
  pkg/snapshot/snapshotter/types.go
  pkg/snapstore/types.go
Labels: area/robustness, component/etcd-backup-restore, kind/api-change, kind/enhancement, needs/lgtm, needs/ok-to-test, needs/review, platform/all

#211 Add snapstore bucket-related metrics
  doc/usage/metrics.md
  pkg/metrics/metrics.go
  pkg/miscellaneous/miscellaneous.go
  pkg/snapshot/snapshotter/snapshotter.go
Labels: area/backup, area/monitoring, component/etcd-backup-restore, needs/lgtm, needs/ok-to-test, needs/review, platform/all

#217 Add documentation for forced manual restore
  doc/usage/manual_restoration.md
Labels: area/documentation, component/etcd-backup-restore, needs/lgtm, needs/ok-to-test, needs/review

#218 Update integration test job image
  .ci/pipeline_definitions
Labels: component/etcd-backup-restore, kind/bug, needs/lgtm, needs/ok-to-test

#222 Skip the full snapshot if initial delta snapshot is taken and
  chart/etcd-backup-restore/templates/etcd-bootstrap-configmap.yaml
  doc/usage/getting_started.md
  pkg/server/backuprestoreserver.go
  pkg/snapshot/snapshotter/snapshotter.go
Labels: needs/ok-to-test, reviewed/lgtm
