Repository gardener/etcd-backup-restore, pull requests merged in 2021-05, with the labels that each got.

#334 Updated number of chunks while uploading to never exceed the cloud provider limits.
  pkg/snapstore/gcs_snapstore.go
  pkg/snapstore/oss_snapstore.go
  pkg/snapstore/s3_snapstore.go
  pkg/snapstore/swift_snapstore.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#336 [rel-v0.12] Update cc/job-image-golang to 0.12.0
  .ci/pipeline_definitions
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs

#337 Update cc/job-image-golang to 0.12.0
  .ci/pipeline_definitions
Labels: reviewed/lgtm, reviewed/ok-to-test, size/xs

#339 Use testmachinery base image for integration_tests
  .ci/pipeline_definitions
Labels: needs/ok-to-test, needs/review, size/xs

#340 Use testmachinery base image for integration_tests
  .ci/pipeline_definitions
Labels: needs/ok-to-test

#335 Updated number of chunks while uploading to never exceed the cloud provider limits.
  pkg/snapstore/gcs_snapstore.go
  pkg/snapstore/oss_snapstore.go
  pkg/snapstore/s3_snapstore.go
  pkg/snapstore/swift_snapstore.go
Labels: needs/ok-to-test, needs/review, size/xs
