Repository gardener/etcd-backup-restore, pull requests merged in 2021-04, with the labels that each got.

#319 depend on publish-trait rather than injected step(s)
  .ci/pipeline_definitions
Labels: needs/ok-to-test, needs/review, size/xs

#320 Refactor pipeline def rel v0.11.0
  .ci/pipeline_definitions
Labels: needs/ok-to-test, needs/review, reviewed/ok-to-test, size/s

#315 Added Auto-Compaction for embedded Etcd and Update helm-charts to run auto-compaction on Etcd.
  chart/etcd-backup-restore/templates/etcd-bootstrap-configmap.yaml
  chart/etcd-backup-restore/templates/etcd-statefulset.yaml
  chart/etcd-backup-restore/values.yaml
  example/00-backup-restore-server-config.yaml
  pkg/snapshot/restorer/init.go
  pkg/snapshot/restorer/restorer.go
  pkg/snapshot/restorer/restorer_test.go
  pkg/snapshot/restorer/types.go
Labels: needs/ok-to-test, needs/review, reviewed/do-not-merge, size/s

#326 Added new metric to capture any snapshotter error
  .gitignore
  pkg/metrics/metrics.go
  pkg/server/backuprestoreserver.go
  pkg/snapshot/snapshotter/garbagecollector.go
Labels: needs/changes, needs/ok-to-test, needs/review, size/s

#327 Move bootstrap script out of helm chart
  .ci/integration_test
  .ci/performance_regression_test
  chart/etcd-backup-restore/templates/etcd-bootstrap-configmap.yaml
  chart/etcd-backup-restore/templates/etcd-configmap.yaml
  chart/etcd-backup-restore/templates/etcd-statefulset.yaml
  chart/etcd-backup-restore/values.yaml
  doc/development/testing_and_dependencies.md
  doc/usage/manual_restoration.md
  test/perf/regression/resources/etcd/configmap.yaml
  test/perf/regression/resources/etcd/pod.yaml
Labels: area/backup, component/etcd-backup-restore, needs/changes, needs/ok-to-test, needs/review, needs/second-opinion, size/l
