Repository gardener/etcd-backup-restore, pull requests merged in 2022-03, with the labels that each got.

#446 Add feature parity for s3 compliant providers
  example/storage-provider-secrets/01-aws-s3-storage-secret.yaml
  pkg/snapstore/s3_snapstore.go
Labels: needs/changes, needs/review, size/s, needs/ok-to-test

#448 Some improvements in logging.
  pkg/compressor/compressor.go
  pkg/snapshot/snapshotter/snapshotter.go
Labels: size/xs, reviewed/lgtm, needs/ok-to-test

#452 Fixed bug in compactor pkg where etcd defragmentation was started be…
  pkg/compactor/compactor.go
  pkg/defragmentor/defrag_test.go
Labels: size/xs, reviewed/lgtm, needs/ok-to-test

#453 Don't fail the Ownercheck when DNS resolve lookup fails.
  pkg/common/checkeractionwatchdog.go
  pkg/common/checkeractionwatchdog_test.go
  pkg/common/ownerchecker.go
  pkg/server/backuprestoreserver.go
Labels: size/s, reviewed/lgtm, needs/ok-to-test

#455 To capture the Full snapshot time taken and compression time taken
  pkg/etcdutil/etcdutil.go
  pkg/types/compactor.go
  pkg/types/etcdconnection.go
Labels: size/xs, reviewed/lgtm, needs/ok-to-test

#419 Introduced endpoint in http server for backup restorer.
  Makefile
  pkg/server/httpAPI.go
Labels: size/s, reviewed/lgtm, needs/ok-to-test
