Repository gardener/etcd-backup-restore, pull requests merged in 2022-09, with the labels that each got.

#522 Added the new metrics needed to be exposed for multi-node etcd.
  pkg/etcdutil/etcdutil.go
  pkg/initializer/initializer.go
  pkg/leaderelection/leaderelection.go
  pkg/member/member_control.go
  pkg/metrics/metrics.go
  pkg/miscellaneous/miscellaneous.go
  pkg/server/backuprestoreserver.go
Labels: reviewed/lgtm, needs/ok-to-test, size/m

#521 Handling the boltDB panic in case of database found to be corrupt.
  pkg/initializer/validator/datavalidator.go
  pkg/initializer/validator/types.go
  pkg/initializer/validator/validator_suite_test.go
Labels: size/s, reviewed/lgtm, needs/ok-to-test

#530 Enhance etcd lease to add peer url enabled status as an annotation
  pkg/health/heartbeat/heartbeat.go
  pkg/health/heartbeat/heartbeat_test.go
  pkg/initializer/initializer.go
  pkg/initializer/validator/datavalidator_test.go
  pkg/leaderelection/leaderelection_test.go
  pkg/member/member_control.go
  pkg/member/member_control_test.go
  pkg/miscellaneous/miscellaneous.go
  pkg/miscellaneous/miscellaneous_test.go
  pkg/miscellaneous/testdata/invalid_config.yaml
  pkg/miscellaneous/testdata/valid_config.yaml
  pkg/server/backrestoreserver_test.go
  pkg/server/backuprestoreserver.go
  pkg/snapshot/restorer/restorer.go
  pkg/snapshot/restorer/restorer_test.go
  pkg/snapshot/snapshotter/snapshotter_test.go
  pkg/snapstore/ocs_s3_snapstore.go
  test/e2e/integration/cloud_backup_test.go
  test/utils/utils.go
Labels: reviewed/do-not-merge, size/xl, reviewed/lgtm, needs/ok-to-test

#507 Added insecureSkipVerify and trustedCaCert for AWS S3 implementation …
  doc/usage/getting_started.md
  example/storage-provider-secrets/01-aws-s3-storage-secret.yaml
  pkg/snapstore/s3_snapstore.go
Labels: needs/review, size/s, needs/ok-to-test

#532 Fix the ProbeEtcd timeout.
  pkg/server/backuprestoreserver.go
  pkg/snapshot/snapshotter/snapshotter.go
  pkg/types/leaderelection.go
Labels: size/xs, reviewed/lgtm, needs/ok-to-test

#534 Member Peer URL not updated when scaled to multi-node, scale identification is also not correct
  pkg/miscellaneous/miscellaneous.go
  pkg/miscellaneous/miscellaneous_test.go
  pkg/server/backrestoreserver_test.go
  pkg/server/backuprestoreserver.go
  pkg/server/httpAPI.go
Labels: reviewed/lgtm, needs/ok-to-test, size/m

#496 Fix the integration tests to run them locally.
  .ci/integration_test
Labels: size/xs, reviewed/lgtm, needs/ok-to-test

#535 Update to golang 1.18.6
  .ci/pipeline_definitions
  build/Dockerfile
Labels: size/xs, needs/changes, needs/review, needs/ok-to-test

#536 Cherry pick commits for branch rel-v0.20
  .ci/pipeline_definitions
  build/Dockerfile
  pkg/miscellaneous/miscellaneous.go
  pkg/miscellaneous/miscellaneous_test.go
  pkg/server/backrestoreserver_test.go
  pkg/server/backuprestoreserver.go
  pkg/server/httpAPI.go
  pkg/snapshot/snapshotter/snapshotter.go
  pkg/types/leaderelection.go
Labels: size/l, reviewed/lgtm, needs/ok-to-test

#537 To decrease the likelihood of race condition while closing the snapshotter.
  pkg/server/backuprestoreserver.go
  pkg/snapshot/snapshotter/snapshotter.go
Labels: size/xs, reviewed/lgtm, needs/ok-to-test

#540 UpdateMemberPeerURL only logs an error in case of failure
  pkg/server/backuprestoreserver.go
Labels: size/xs, needs/changes, needs/review, needs/ok-to-test, needs/cherry-pick

#542 [rel-v0.20] UpdateMemberPeerURL only logs an error in case of failure
  pkg/server/backuprestoreserver.go
Labels: size/xs, needs/review, needs/ok-to-test
