Repository gardener/etcd-backup-restore, pull requests merged in 2022-02, with the labels that each got.

#427 Reduce verbosity of leadershipStatus check log
  pkg/leaderelection/leaderelection.go
Labels: size/xs, reviewed/lgtm, needs/ok-to-test

#405 Upgrade the Go from v1.14 to v1.16.
  go.mod
  go.sum
Labels: reviewed/do-not-merge, size/xs, reviewed/lgtm, needs/ok-to-test

#410 Renew snapshot leases even if snapshot skipped
  pkg/health/heartbeat/heartbeat.go
  pkg/health/heartbeat/heartbeat_test.go
Labels: needs/changes, needs/review, size/s, needs/ok-to-test, merge/squash

#417 Refactor and Removed some unnecessary code.
  cmd/compact.go
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/defragmentor/defrag.go
  pkg/defragmentor/defrag_test.go
  pkg/etcdutil/etcdutil.go
  pkg/etcdutil/types.go
  pkg/types/etcdconnection.go
Labels: size/s, reviewed/lgtm, needs/ok-to-test, merge/squash

#430 update tm scripts
  .ci/pipeline_definitions
  .ci/tm-tests-playground
Labels: size/xs, reviewed/lgtm, needs/ok-to-test

#411 Decouple the readinessProbe of etcd and Snapshotter
  cmd/options.go
  example/00-backup-restore-server-config.yaml
  pkg/backoff/exponentialbackoff.go
  pkg/backoff/exponentialbackoff_suite_test.go
  pkg/backoff/exponentialbackoff_test.go
  pkg/server/backuprestoreserver.go
  pkg/server/httpAPI.go
  pkg/server/init.go
  pkg/server/types.go
  pkg/types/exponentialbackoff.go
Labels: needs/changes, needs/review, needs/second-opinion, size/l, needs/ok-to-test, merge/squash

#438 Don't hide error when creating K8s client
  pkg/miscellaneous/miscellaneous.go
Labels: kind/enhancement, size/xs, needs/review, area/ops-productivity, needs/ok-to-test

#440 Handle SIGTERM in main signal handler
  main.go
Labels: size/xs, reviewed/lgtm, needs/ok-to-test

#435 To dynamically load IaaS credentials during runtime
  cmd/snapshot.go
  pkg/compactor/compactor_test.go
  pkg/initializer/validator/validator_suite_test.go
  pkg/server/backuprestoreserver.go
  pkg/snapshot/snapshotter/garbagecollector.go
  pkg/snapshot/snapshotter/snapshotter.go
  pkg/snapshot/snapshotter/snapshotter_test.go
  pkg/snapstore/abs_snapstore.go
  pkg/snapstore/gcs_snapstore.go
  pkg/snapstore/oss_snapstore.go
  pkg/snapstore/s3_snapstore.go
  pkg/snapstore/swift_snapstore.go
  pkg/snapstore/utils.go
  test/utils/utils.go
Labels: size/xl, reviewed/lgtm, needs/ok-to-test

#436 Updated the document.
  doc/usage/getting_started.md
  example/storage-provider-secrets/00-azure-blob-storage-secret.yaml
  example/storage-provider-secrets/01-aws-s3-storage-secret.yaml
  example/storage-provider-secrets/02-openstack-swift-storage-secret.yaml
  example/storage-provider-secrets/03-ali-cloud-object-storage-secret.yaml
  example/storage-provider-secrets/04-google-cloud-storage-secret.yaml
Labels: reviewed/lgtm, needs/ok-to-test, size/m

#441 Reduce verbosity of leader current state log
  pkg/leaderelection/leaderelection.go
Labels: size/xs, needs/review, needs/ok-to-test

#431 Add support for custom endpoints in S3 snapstore
  doc/usage/getting_started.md
  pkg/snapstore/s3_snapstore.go
Labels: size/xs, reviewed/lgtm, needs/ok-to-test
