Repository gardener/etcd-backup-restore, pull requests merged in 2022-04, with the labels that each got.

#458 Reduce verbosity of Renew member lease log.
  pkg/health/heartbeat/heartbeat.go
Labels: size/xs, reviewed/lgtm, needs/ok-to-test

#459 Fix defragmentation fail issue which occurs due certificate IP SANs for single node etcd.
  pkg/miscellaneous/miscellaneous.go
Labels: size/xs, reviewed/lgtm, needs/ok-to-test

#460 Reduce verbosity of Renew member lease logs.
  pkg/health/heartbeat/heartbeat.go
Labels: size/xs, reviewed/lgtm, needs/ok-to-test

#462 Fix AWS_FORCE_PATH_STYLE env parsing
  pkg/snapstore/s3_snapstore.go
Labels: size/xs, needs/review, needs/ok-to-test

#464 v0.15 Fix AWS_FORCE_PATH_STYLE env parsing
  pkg/snapstore/s3_snapstore.go
Labels: size/xs, needs/review, needs/ok-to-test

#465 OCS S3 Snapstore support access information via mounted secret
  doc/usage/getting_started.md
  example/storage-provider-secrets/05-openshift-container-storage-secret.yaml
  pkg/snapstore/ocs_s3_snapstore.go
  pkg/snapstore/utils.go
Labels: needs/changes, needs/review, needs/ok-to-test, size/m, merge/squash

#468 Added a file containing shoot identifier to safe guard against wrong volume mount.
  pkg/initializer/initializer.go
  pkg/initializer/validator/datavalidator.go
  pkg/initializer/validator/datavalidator_test.go
  pkg/initializer/validator/types.go
Labels: needs/changes, needs/review, size/s, needs/ok-to-test

#467 Throw Fatal error to avoid potential deadlock condition.
  pkg/health/heartbeat/heartbeat.go
  pkg/server/backuprestoreserver.go
Labels: size/xs, needs/review, needs/ok-to-test

#470 Added a file containing shoot identifier to safe guard against wrong volume mount.
  pkg/initializer/initializer.go
  pkg/initializer/validator/datavalidator.go
  pkg/initializer/validator/datavalidator_test.go
  pkg/initializer/validator/types.go
Labels: needs/ok-to-test
