Repository gardener/etcd-backup-restore, pull requests merged in 2022-08, with the labels that each got.

#509 Adds a feature of single member restoration in multi-node etcd.
  pkg/errors/error.go
  pkg/initializer/initializer.go
  pkg/initializer/validator/datavalidator.go
  pkg/initializer/validator/types.go
  pkg/leaderelection/leaderelection.go
  pkg/leaderelection/leaderelection_test.go
  pkg/member/member_control.go
  pkg/member/member_control_test.go
  pkg/miscellaneous/miscellaneous.go
  pkg/miscellaneous/miscellaneous_test.go
  pkg/server/backuprestoreserver.go
  pkg/server/httpAPI.go
  pkg/types/leaderelection.go
Labels: size/xl, reviewed/lgtm, needs/ok-to-test

#513 Add serviceEndpoint to connect to etcd
  pkg/etcdutil/client/option.go
  pkg/etcdutil/etcdutil.go
  pkg/member/member_control.go
  pkg/miscellaneous/miscellaneous.go
  pkg/server/httpAPI.go
  pkg/types/etcdconnection.go
  pkg/types/restorer.go
Labels: reviewed/lgtm, needs/ok-to-test, size/m

#520 Upgrade alpine image used to build backup-restore image
  build/Dockerfile
Labels: size/xs, reviewed/lgtm, needs/ok-to-test
