Repository gardener/etcd-backup-restore, pull requests merged in 2022-07, with the labels that each got.

#487 Add support for etcd cluster scale up
  cmd/initializer.go
  cmd/options.go
  pkg/initializer/initializer.go
  pkg/initializer/types.go
  pkg/member/member_control.go
  pkg/member/member_control_suite_test.go
  pkg/member/member_control_test.go
  pkg/miscellaneous/miscellaneous.go
  pkg/server/backuprestoreserver.go
  pkg/server/httpAPI.go
Labels: reviewed/do-not-merge, needs/changes, needs/review, size/xl, needs/second-opinion, needs/ok-to-test

#499 Build Multi-Arch Images 📦
  .ci/build
  .ci/pipeline_definitions
  Makefile
  build/Dockerfile
Labels: kind/enhancement, reviewed/ok-to-test, area/dev-productivity, needs/review, size/s, needs/ok-to-test, area/delivery

#501 Temp fix: skip single member restoration in case of data-dir invalid.
  pkg/initializer/initializer.go
  pkg/initializer/validator/datavalidator.go
  pkg/initializer/validator/types.go
  pkg/member/member_control.go
  pkg/member/member_control_test.go
  pkg/miscellaneous/miscellaneous.go
  pkg/miscellaneous/miscellaneous_test.go
  pkg/server/httpAPI.go
Labels: needs/second-opinion, size/l, needs/ok-to-test

#505 Assigned the correct Peer Address to Etcd after it restores from the backup-bucket.
  cmd/restore.go
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/initializer/initializer.go
  pkg/member/member_control.go
  pkg/server/backuprestoreserver.go
  pkg/server/httpAPI.go
  pkg/snapshot/restorer/restorer.go
  pkg/snapshot/restorer/restorer_test.go
Labels: reviewed/lgtm, needs/ok-to-test, size/m

#506 Don't update peer URL when promoting member
  pkg/member/member_control.go
  pkg/snapshot/restorer/restorer.go
Labels: size/xs, needs/changes, needs/review, needs/ok-to-test

#508 Cherry pick changes for rel v0.18.1
  cmd/restore.go
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/initializer/initializer.go
  pkg/initializer/validator/datavalidator.go
  pkg/initializer/validator/types.go
  pkg/member/member_control.go
  pkg/member/member_control_test.go
  pkg/miscellaneous/miscellaneous.go
  pkg/miscellaneous/miscellaneous_test.go
  pkg/server/backuprestoreserver.go
  pkg/server/httpAPI.go
  pkg/snapshot/restorer/restorer.go
  pkg/snapshot/restorer/restorer_test.go
Labels: needs/review, size/xl, needs/second-opinion, needs/ok-to-test

#493 Drop the feature of passing storage container secrets through Environment Variable.
  doc/usage/getting_started.md
  pkg/snapstore/abs_snapstore.go
  pkg/snapstore/ocs_s3_snapstore.go
  pkg/snapstore/oss_snapstore.go
  pkg/snapstore/s3_snapstore.go
  pkg/snapstore/swift_snapstore.go
Labels: reviewed/lgtm, needs/ok-to-test, size/m

#510 Fix svc endpoint extraction
  pkg/miscellaneous/miscellaneous.go
Labels: kind/bug, priority/critical, size/xs, reviewed/lgtm, needs/ok-to-test, area/control-plane, priority/1

#511 Cherry pick changes for rel v0.18.2
  pkg/miscellaneous/miscellaneous.go
Labels: size/xs, reviewed/lgtm, needs/ok-to-test

#512 [rel-v0.18] Add serviceEndpoint to connect to etcd
  pkg/etcdutil/client/option.go
  pkg/etcdutil/etcdutil.go
  pkg/member/member_control.go
  pkg/miscellaneous/miscellaneous.go
  pkg/server/httpAPI.go
  pkg/types/etcdconnection.go
  pkg/types/restorer.go
Labels: reviewed/ok-to-test, reviewed/lgtm, size/m
