Repository gardener/etcd-backup-restore, pull requests merged in 2022-05, with the labels that each got.

#471 Throw Fatal error to avoid potential deadlock.
  pkg/health/heartbeat/heartbeat.go
  pkg/health/heartbeat/heartbeat_suite_test.go
  pkg/health/heartbeat/heartbeat_test.go
  pkg/server/backuprestoreserver.go
Labels: needs/changes, needs/review, size/s, needs/ok-to-test

#476 Fixes copy operation for Swift snapstore
  pkg/snapstore/swift_snapstore.go
Labels: size/xs, needs/review, needs/ok-to-test

#477 Fixes copy operation for Swift snapstore
  pkg/snapstore/swift_snapstore.go
Labels: size/xs, needs/review, needs/ok-to-test

#478 Kill etcd process exactly before taking a final snapshot
  pkg/server/backuprestoreserver.go
Labels: needs/review, size/s, needs/ok-to-test

#479 [cherry-pick of #478 ]Kill etcd process exactly before taking a final snapshot
  pkg/server/backuprestoreserver.go
Labels: needs/review, size/s, needs/ok-to-test

#463 Add feature parity for s3 compliant providers.
  pkg/snapstore/s3_snapstore.go
Labels: size/xs, reviewed/lgtm, needs/ok-to-test

#480 Added a timer while opening a boltDB and improve error handling for verifying database.
  pkg/initializer/initializer.go
  pkg/initializer/validator/datavalidator.go
  pkg/initializer/validator/types.go
Labels: needs/review, size/s, needs/ok-to-test
