Repository gardener/etcd-backup-restore, pull requests merged in 2023-08, with the labels that each got.

#649 Skip scale-up checks for first member of etcd cluster.
  pkg/initializer/initializer.go
Labels: reviewed/ok-to-test, size/xs, reviewed/lgtm, needs/ok-to-test

#655 Skip scale-up checks for first member of etcd cluster. (#649)
  pkg/initializer/initializer.go
Labels: kind/bug, size/xs, needs/review, needs/ok-to-test

#654 Skip scale-up checks for first member of etcd cluster. (#649)
  pkg/initializer/initializer.go
Labels: kind/bug, size/xs, needs/review, needs/ok-to-test

#656 move ioutil func calls to different pkg as ioutil has been deprecated.
  pkg/server/httpAPI.go
Labels: reviewed/ok-to-test, size/xs, reviewed/lgtm, needs/ok-to-test

#641 Introduce persona-based docs
  .docforge/manifest.yaml
  README.md
  docs/development/local_setup.md
  docs/development/new_cp_support.md
  docs/development/testing_and_dependencies.md
  docs/development/tests.md
  docs/images/etcd-backup-restore-sequence-diagram.jpg
  docs/images/etcd-backup-restore.jpg
  docs/images/leaderElection_stateDiagram.png
  docs/images/profile-fast-drain.png
  docs/images/profile-high-rate-events.png
  docs/images/restorer-sequence-diagram.png
  docs/operations/generating_ssl_certificates.md
  docs/operations/getting_started.md
  docs/operations/leader_election.md
  docs/operations/manual_restoration.md
  docs/operations/metrics.md
  docs/proposals/design.md
  docs/proposals/high_watch_event_ingress_rate.md
  docs/proposals/restoration.md
  docs/proposals/validation.md
Labels: size/s, reviewed/lgtm, needs/ok-to-test

#657 Minor restructuring of docs section
  .docforge/manifest.yaml
  README.md
  docs/deployment/getting_started.md
  docs/development/new_cp_support.md
  docs/proposals/restoration.md
  docs/usage/garbage_collection.md
Labels: reviewed/ok-to-test, size/s, reviewed/lgtm, area/documentation, needs/ok-to-test
