Repository gardener/etcd-backup-restore, pull requests merged in 2023-07, with the labels that each got.

#644 Add CVE categorization for etcd-backup-restore
  .ci/pipeline_definitions
Labels: size/xs, needs/review, needs/ok-to-test

#637 Use distroless images and use user home dir to create files
  build/Dockerfile
  pkg/server/httpAPI.go
  pkg/snapstore/utils.go
Labels: size/xs, reviewed/lgtm, needs/ok-to-test, merge/squash

#640 Implement Configurable Retention Period for Delta Snapshots
  doc/usage/garbage_collection.md
  pkg/snapshot/snapshotter/garbagecollector.go
  pkg/snapshot/snapshotter/snapshotter_test.go
  pkg/types/snapshotter.go
Labels: size/xl, needs/second-opinion, needs/ok-to-test
