Repository gardener/etcd-backup-restore, pull requests merged in 2023-02, with the labels that each got.

#571 Add enhancement github issue template.
  .github/ISSUE_TEMPLATE/enhancement_request.md
Labels: size/xs, needs/review, needs/ok-to-test

#580 Added support for Application credentials to authenticate openstack.
  example/storage-provider-secrets/02-openstack-swift-storage-secret.yaml
  pkg/snapstore/swift_snapstore.go
Labels: reviewed/lgtm, needs/ok-to-test, size/m

#582 Update member_control.go
  pkg/member/member_control.go
Labels: size/xs, needs/changes, needs/review, needs/ok-to-test

#581 Update `k8s.io/client-go` to a human-readable version
  go.mod
  vendor/modules.txt
Labels: kind/enhancement, size/xs, reviewed/lgtm, needs/ok-to-test

#564 Fix the bug of falsely wrong annotation added to etcd-member lease of TLS not enabled.
  pkg/health/heartbeat/heartbeat.go
  pkg/health/heartbeat/heartbeat_test.go
  pkg/member/member_control.go
  pkg/member/member_control_test.go
  pkg/miscellaneous/miscellaneous.go
  pkg/miscellaneous/miscellaneous_test.go
  pkg/server/backrestoreserver_test.go
  pkg/server/backuprestoreserver.go
Labels: needs/changes, needs/review, needs/ok-to-test, size/m

#574 Enhances the decision to take full snapshot during startup to avoid missing of any full-snapshot.
  pkg/miscellaneous/miscellaneous.go
  pkg/server/backuprestoreserver.go
  pkg/snapshot/snapshotter/snapshotter.go
  pkg/snapshot/snapshotter/snapshotter_test.go
Labels: size/l, reviewed/lgtm, needs/ok-to-test

#590 Update to golang 1.19.5, alpine 3.15.7
  .ci/pipeline_definitions
  build/Dockerfile
Labels: kind/enhancement, area/security, size/xs, needs/review, needs/ok-to-test, area/delivery
