Repository gardener/etcd-backup-restore, pull requests merged in 2024-04, with the labels that each got.

#713 Update alpine base image version to 3.18.6
  build/Dockerfile
Labels: kind/enhancement, size/xs, needs/review, needs/ok-to-test, area/os

#723 Add documentation to run `etcdbrctl` as a process locally
  docs/development/local_setup.md
Labels: needs/changes, needs/review, size/s, needs/ok-to-test

#719 Setup SSE with customer provided keys (SSE-C) for S3-compatible providers
  chart/etcd-backup-restore/values.yaml
  docs/deployment/getting_started.md
  pkg/snapstore/generic_s3_snapstore.go
  pkg/snapstore/s3_snapstore.go
  pkg/snapstore/snapstore_test.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/m

#728 Set appropriate SSE Customer Key and MD5 in `S3SnapStore.uploadPart()` for SSE-C
  pkg/snapstore/s3_snapstore.go
Labels: size/xs, needs/review, needs/ok-to-test
