Repository gardener/etcd-backup-restore, pull requests merged in 2024-01, with the labels that each got.

#700 Fix artifact registry issue
  Makefile
Labels: reviewed/ok-to-test, size/xs, reviewed/lgtm, needs/ok-to-test

#701 Fix artifact registry issue
  Makefile
Labels: size/xs, needs/review, needs/ok-to-test

#703 Fix regression in chunk deletion for openstack provider
  pkg/snapshot/snapshotter/garbagecollector.go
  pkg/snapshot/snapshotter/snapshotter_test.go
  pkg/snapstore/snapstore_test.go
  pkg/snapstore/swift_snapstore.go
  pkg/snapstore/swift_snapstore_test.go
Labels: reviewed/ok-to-test, platform/openstack, size/l, reviewed/lgtm, area/backup, needs/ok-to-test, merge/squash, needs/cherry-pick

#704 [rel-v0.24] Fix regression in chunk deletion for openstack provider (#703)
  pkg/snapshot/snapshotter/garbagecollector.go
  pkg/snapshot/snapshotter/snapshotter_test.go
  pkg/snapstore/snapstore_test.go
  pkg/snapstore/swift_snapstore.go
  pkg/snapstore/swift_snapstore_test.go
Labels: kind/bug, needs/review, needs/second-opinion, size/l, area/backup, needs/ok-to-test

#709 Add etcd team to component descriptor
  .ci/pipeline_definitions
Labels: kind/enhancement, reviewed/ok-to-test, size/xs, reviewed/lgtm, needs/ok-to-test, area/delivery
