Repository gardener/etcd-backup-restore, pull requests merged in 2024-11, with the labels that each got.

#793 Improved error handling in deletion of delta snapshots during snapshot garbage collection
  pkg/snapshot/snapshotter/garbagecollector.go
  pkg/snapshot/snapshotter/snapshotter_test.go
Labels: needs/changes, needs/review, needs/ok-to-test, size/m

#801 Use `x.y.0` versions of the Go Toolchain only
  go.mod
Labels: size/xs, needs/review, needs/ok-to-test, dependencies

#802 [rel-v0.31] Use `x.y.0` versions of the Go Toolchain only (#801)
  go.mod
Labels: size/xs, needs/review, needs/ok-to-test

#803 Enhance the `check` make target to ensure the Go version adheres to `x.y.0`.
  .ci/check
  pkg/mock/etcd/clientv3/mocks.go
  pkg/mock/etcdutil/client/mocks.go
Labels: size/xs, area/dev-productivity, needs/review, kind/cleanup, needs/ok-to-test

#804 Prevent skipping scheduled full snapshots when there are no new updates
  pkg/snapshot/snapshotter/snapshotter.go
Labels: size/xs, reviewed/lgtm, needs/ok-to-test

#781 Add `Container level WORM` immutable object support for Azure Blob Storage.
  docs/usage/immutable_snapshots.md
  pkg/snapshot/snapshotter/garbagecollector.go
  pkg/snapstore/abs_snapstore.go
  pkg/snapstore/abs_snapstore_test.go
  pkg/snapstore/gcs_snapstore.go
  pkg/snapstore/snapstore_test.go
  pkg/types/snapstore.go
Labels: needs/changes, needs/review, area/robustness, area/backup, needs/ok-to-test, size/m, area/storage, platform/azure

#806 Improve `docs/usage/immutable_snapshots.md`, adding example commands to make buckets immutable.
  docs/usage/immutable_snapshots.md
Labels: size/xs, needs/review, area/backup, area/documentation, needs/ok-to-test
