Repository gardener/etcd-backup-restore, pull requests merged in 2024-09, with the labels that each got.

#771 Removed useless error handling.
  pkg/initializer/initializer.go
Labels: size/xs, needs/review, needs/ok-to-test

#780 Enhance the `docker-build` make target to build for multiple platforms.
  Makefile
Labels: kind/enhancement, reviewed/ok-to-test, size/xs, area/dev-productivity, reviewed/lgtm, needs/ok-to-test

#776 Add `Bucket Lock` immutable object support for Google Cloud Storage.
  docs/usage/immutable_snapshots.md
  pkg/compactor/compactor_test.go
  pkg/miscellaneous/miscellaneous.go
  pkg/miscellaneous/miscellaneous_test.go
  pkg/snapshot/copier/copier.go
  pkg/snapshot/snapshotter/garbagecollector.go
  pkg/snapshot/snapshotter/snapshotter_test.go
  pkg/snapstore/abs_snapstore.go
  pkg/snapstore/failed_snapstore.go
  pkg/snapstore/gcs_snapstore.go
  pkg/snapstore/gcs_snapstore_test.go
  pkg/snapstore/local_snapstore.go
  pkg/snapstore/oss_snapstore.go
  pkg/snapstore/s3_snapstore.go
  pkg/snapstore/snapshot_test.go
  pkg/snapstore/snapstore_test.go
  pkg/snapstore/swift_snapstore.go
  pkg/types/snapstore.go
  test/e2e/integration/cloud_backup_test.go
  test/e2e/integrationcluster/backup_test.go
  test/e2e/integrationcluster/utils.go
Labels: platform/gcp, needs/changes, needs/review, needs/second-opinion, area/robustness, size/l, area/backup, needs/ok-to-test, area/storage, merge/squash
