Repository gardener/etcd-backup-restore, pull requests merged in 2024-03, with the labels that each got.

#717 Updated the .reuse/dep5 file.
  .reuse/dep5
Labels: size/xs, reviewed/lgtm, needs/ok-to-test

#710 Improve `etcd-backup-restore`'s behavior with OpenStack Swift's Dynamic Large Objects for better error handling, and improved unit tests
  pkg/snapstore/snapstore_test.go
  pkg/snapstore/swift_snapstore.go
  pkg/snapstore/swift_snapstore_test.go
Labels: kind/enhancement, reviewed/ok-to-test, platform/openstack, kind/test, size/l, reviewed/lgtm, area/backup, needs/ok-to-test, area/testing

#711 Full snapshot lease update retry on failure
  pkg/compactor/compactor.go
  pkg/health/heartbeat/heartbeat.go
  pkg/health/heartbeat/heartbeat_test.go
  pkg/server/backuprestoreserver.go
  pkg/snapshot/snapshotter/fullsnapshotleaseupdate.go
  pkg/snapshot/snapshotter/snapshotter.go
  pkg/snapshot/snapshotter/snapshotter_test.go
  pkg/types/health.go
Labels: kind/bug, needs/changes, needs/review, needs/second-opinion, size/l, needs/ok-to-test

#720 Fix a full snapshot lease renewal decision
  pkg/health/heartbeat/heartbeat.go
Labels: size/xs, needs/review, needs/ok-to-test

#721 Fix statefulset to treat provider config env vars as optional
  chart/etcd-backup-restore/templates/etcd-statefulset.yaml
Labels: size/xs, needs/review, area/usability, kind/task, needs/ok-to-test

#680 Do not check SSR State when Snapshotter should be stopped
  pkg/server/backuprestoreserver.go
Labels: size/xs, needs/review, needs/ok-to-test, merge/squash

#697 [FakeGCS] Add a new field `emulatorEnabled` in gcp secret & configure Gcloud client for GCS Emulator
  chart/etcd-backup-restore/templates/etcd-backup-secret.yaml
  chart/etcd-backup-restore/templates/etcd-statefulset.yaml
  chart/etcd-backup-restore/values.yaml
  example/storage-provider-secrets/04-google-cloud-storage-secret.yaml
  pkg/snapstore/abs_snapstore.go
  pkg/snapstore/gcs_snapstore.go
  pkg/snapstore/snapshot.go
  pkg/snapstore/snapstore.go
  pkg/snapstore/snapstore_test.go
  pkg/types/snapstore.go
Labels: kind/enhancement, area/dev-productivity, platform/gcp, reviewed/lgtm, area/backup, needs/ok-to-test, size/m, area/testing
