Repository gardener/etcd-backup-restore, pull requests merged in 2025-02, with the labels that each got.

#837 Moved some of the unit tests from `pkg/defragmentor_test` to `pkg/etcdutiil_test`
  pkg/defragmentor/defrag_test.go
  pkg/defragmentor/defragmentor_suite_test.go
  pkg/etcdutil/etcdutil_suite_test.go
  pkg/etcdutil/etcdutil_test.go
Labels: needs/ok-to-test

#846 Removed dead code.
  pkg/snapshot/restorer/restorer.go
Labels: needs/review, size/s, kind/cleanup, needs/ok-to-test

#841 Refactor the enabling of immutable snapshots doc
  docs/usage/enabling_immutable_snapshots.md
  pkg/snapstore/s3_snapstore.go
Labels: kind/enhancement, reviewed/ok-to-test, size/l, reviewed/lgtm, area/documentation, needs/ok-to-test

#842 Upgrade to `go1.23.6`.
  .ci/pipeline_definitions
  build/Dockerfile
Labels: reviewed/ok-to-test, area/security, size/xs, area/quality, kind/task, reviewed/lgtm, needs/ok-to-test, area/compliance

#845 Fixed a bug which causes restoration to fail when first delta snapshot completely overlaps latest full snapshot.
  pkg/snapshot/restorer/restorer.go
Labels: kind/bug, reviewed/ok-to-test, size/xs, area/disaster-recovery, reviewed/lgtm, needs/ok-to-test
