Repository gardener/etcd-backup-restore, pull requests merged in 2025-01, with the labels that each got.

#824 Tag docker images built via pipeline release process as `latest`
  .ci/pipeline_definitions
Labels: kind/enhancement, size/xs, needs/review, area/usability, needs/ok-to-test

#825 Update github issue and PR templates
  .github/ISSUE_TEMPLATE/backlog-item.md
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement_request.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/flaking-test.md
  .github/ISSUE_TEMPLATE/support.md
  .github/pull_request_template.md
Labels: area/open-source, needs/review, kind/task, needs/ok-to-test, size/m

#826 Fix github issue templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/support.md
Labels: reviewed/ok-to-test, size/xs, area/open-source, needs/review, kind/task

#828 Set `controller-runtime` logger to `log.NullLogSink{}`
  cmd/compact.go
  cmd/copy.go
  cmd/initializer.go
  cmd/options.go
  cmd/restore.go
  cmd/snapshot.go
Labels: kind/bug, size/xs, area/logging, reviewed/lgtm, needs/ok-to-test

#818 Add `Bucket Lock` immutable objects support for AWS S3
  docs/images/S3_immutability_working.png
  docs/usage/enabling_immutable_snapshots.md
  pkg/snapshot/snapshotter/garbagecollector.go
  pkg/snapstore/oss_snapstore.go
  pkg/snapstore/s3_snapstore.go
  pkg/snapstore/s3_snapstore_test.go
  pkg/snapstore/snapstore_test.go
  pkg/types/snapstore.go
Labels: size/xl, needs/second-opinion, needs/ok-to-test

#830 Update etcdbr image tag to latest in helm charts
  chart/etcd-backup-restore/values.yaml
Labels: reviewed/ok-to-test, size/xs, needs/review, kind/task, needs/ok-to-test

#831 Update golang version to 1.23.5
  .ci/pipeline_definitions
  build/Dockerfile
Labels: reviewed/ok-to-test, area/security, size/xs, area/quality, kind/task, reviewed/lgtm, needs/ok-to-test, area/compliance

#833 Added missing header and Updated example/etcd-config.yaml
  example/01-etcd-config.yaml
  pkg/health/heartbeat/heartbeat_suite_test.go
  pkg/health/heartbeat/heartbeat_test.go
Labels: size/xs, needs/review, needs/ok-to-test
